#!/bin/sh
CONFIG="$HOME/.lookfar"
if [ -e "$CONFIG" ] ; then
  . "$CONFIG"
fi
if [ -n "$PORT" ] ; then
  FOREMAN_OPTS="$FOREMAN_OPTS -p $PORT"
fi
export JAVA_OPTS="$JAVA_OPTS -Duser.timezone=UTC"
mvn clean install && foreman start $FOREMAN_OPTS
